// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migration_add_about_aboutstatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration_add_about_aboutstatus));
        
        string IMigrationMetadata.Id
        {
            get { return "202106131435462_migration_add_about_aboutstatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
